FEATURE_GROUP_NAME = 'energy_consumption_fg'
FEATURE_GROUP_VERSION = 1
FEATURE_GROUP_ONL_NAME = 'energy_consumption_onl_fg'
FEATURE_GROUP_ONL_VERSION = 1
FEATURE_VIEW_INF_NAME = 'energy_consumption_onl_view'
FEATURE_VIEW_INF_VERSION = 1
FEATURE_VIEW_ONL_NAME = ''
FEATURE_VIEW_ONL_VERSION = ''